### PR TITLE
Cleanup Package, add css hot reload

### PR DESCRIPTION
**Pull request by RyanLafferty**
# Cleanup Package, add css hot reload 

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [x] Feature
- [x] Refactoring
- [ ] Documentation

## :book: Description

* Added missing tailwindcss dependency
* Added npm-run-all dependency for series and parallel running of scripts
* Refactored scripts to leverage npm-run-all
* Updated start script to clean the dist folder and then run postcss:watch and eleventy:serve scripts in parallel
* Added a postcss transform and css directory watch target to enable hot reloading of css

## :bulb: Context

To enable hot reloading when css changes are made

## :link: Sources

See in code comments

### CODE REVIEW

**Comment by TedGoas** [comment]
@RyanLafferty testing out your PR and everything looks mostly good. When I make a CSS change (say to a file in `/src/assets/css/custom/`), I notice that the site automatically recompiles in terminal, but the browser doesn't reload. Am I doing something wrong?

**Comment by RyanLafferty** [comment]
> 
> 
> @RyanLafferty testing out your PR and everything looks mostly good. When I make a CSS change (say to a file in `/src/assets/css/custom/`), I notice that the site automatically recompiles in terminal, but the browser doesn't reload. Am I doing something wrong?

I tried to reproduce your issue but was unable to 😕

I cloned my fork into a new directory and did a clean install and run. I was able to change the background color of your bio cards which triggered a rebuild and then a reload in the browser which displayed the updated background color.

Test Environment: `Windows 10 WSL (Ubuntu 18.04)`
Location of the styles modified: `src/assets/css/custom/bio.css`

Commands executed:
```bash
# Clone repo
git clone https://github.com/RyanLafferty/Dante.git test-dante

# Change directory
cd test-dante

# Checkout working branch
git checkout 11ty-vredeburg

# Install deps
npm install

# Run start script
npm start
```

Maybe there is an issue with the connection between `eleventy's` `browsersync` setup and your browser?

**Comment by TedGoas** [comment]
Yea it's weird, after it recompiles I see this:
Screen Shot 2021-05-20 at 10 11 32 PM
But no actual browser reload.

However if I edit an `.njk` or `.md` file, the browser reloads without issue.

**Comment by TedGoas** [comment]
Gonna merge this since it's an improvement to what I have now, will see if the hot-reload issue can be resolved separately.

**Pull request merged**
